# Generated by Django 3.0.6 on 2020-07-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password1', models.CharField(max_length=20)),
                ('Password2', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
                ('contend', models.TextField(max_length=200)),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_app.Userdata')),
            ],
        ),
    ]
