# Generated by Django 3.0.6 on 2020-07-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0003_auto_20200706_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='Userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reg_app.Userdata'),
            preserve_default=False,
        ),
    ]
