# Generated by Django 3.0.6 on 2020-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0004_publish_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
