# Generated by Django 3.0.6 on 2020-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0005_auto_20200706_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
