# Generated by Django 3.0.6 on 2020-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0007_auto_20200709_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail1', models.EmailField(max_length=254)),
                ('mail2', models.EmailField(max_length=254)),
                ('mail3', models.EmailField(max_length=254)),
            ],
        ),
    ]
