# Generated by Django 3.0.6 on 2020-07-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0008_topuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuser',
            name='mail2',
        ),
        migrations.RemoveField(
            model_name='topuser',
            name='mail3',
        ),
    ]
