# Generated by Django 3.0.6 on 2020-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0009_auto_20200711_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuser',
            name='mail1',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
