# Generated by Django 3.0.6 on 2020-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0010_auto_20200711_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='contend',
            field=models.TextField(max_length=20000),
        ),
    ]
